services:
  gestion_construccion:
    image: gestion_construccion
    build:
      context: .
      dockerfile: gestion_construccion/Dockerfile

  gestion_construcion.api:
    image: gestion_construcion.api
    build:
      context: .
      dockerfile: gestion_construcion.api/Dockerfile

