version: '3.8'

services:
  # Servicio para la base de datos PostgreSQL
  postgres_db:
    image: postgres:15
    container_name: firmeza_postgres
    environment:
      POSTGRES_DB: gestion_construccion
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Qwe.123*
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Servicio para la aplicaci칩n web ASP.NET Core
  firmeza_web:
    container_name: firmeza_webapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # La aplicaci칩n dentro del contenedor se conectar치 a la base de datos usando el nombre del servicio 'postgres_db'.
      - ConnectionStrings__DefaultConnection=Host=postgres_db;Database=gestion_construccion;Username=postgres;Password=Qwe.123*
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - postgres_db # Le dice a Docker que inicie el contenedor de la base de datos antes que el de la aplicaci칩n.

volumes:
  postgres_data:
```